u-boot: Remove redundant YYLOC global declaration
Fixes build error:
tmp/hosttools/ld: scripts/dtc/dtc-parser.tab.o:(.bss+0x10): multiple definition of `yylloc';

Imported patch from commit 018921ee [source.denx.de]

Signed-off-by: Lothar Rubusch <lothar.rubusch@bytesatwork.ch>