gdb-cross-canadian: fix user/host contamination issue introduced by meta-st-stm32mp layer
This commit fixes the error message below.

Introduced by: meta-st-stm32mp/recipes-devtools/gdb/gdb-cross-canadian_%.bbappend
 as: cp -a ${WORKDIR}/gdbinit ${D}/${bindir}/ preserves host-user-id,
which is not allowed

This commit might be removed if the problem has been fixed on the
meta-st-stm32mp layer.

WARNING: gdb-cross-canadian-arm-9.1-r0 do_package: KeyError in ./package/opt/poky-bytesatwork/3.1.1/sysroots/x86_64-pokysdk-linux/usr/bin/arm-poky-linux-gnueabi/gdbinit
ERROR: gdb-cross-canadian-arm-9.1-r0 do_package: Error executing a python function in exec_python_func() autogenerated:

The stack trace of python calls that resulted in this exception/failure was:
File: 'exec_python_func() autogenerated', lineno: 2, function: <module>
     0001:
 *** 0002:sstate_report_unihash(d)
     0003:
File: '/media/janek/7cd07add-5479-43d8-a522-1292f153b637/workspace/baw/dunfell/m5/bsp-platform-st/sources/poky/meta/classes/sstate.bbclass', lineno: 840, function: sstate_report_unihash
     0836:    report_unihash = getattr(bb.parse.siggen, 'report_unihash', None)
     0837:
     0838:    if report_unihash:
     0839:        ss = sstate_state_fromvars(d)
 *** 0840:        report_unihash(os.getcwd(), ss['task'], d)
     0841:}
     0842:
     0843:#
     0844:# Shell function to decompress and prepare a package for installation
File: '/media/janek/7cd07add-5479-43d8-a522-1292f153b637/workspace/baw/dunfell/m5/bsp-platform-st/sources/poky/bitbake/lib/bb/siggen.py', lineno: 555, function: report_unihash
     0551:
     0552:            if "." in self.method:
     0553:                (module, method) = self.method.rsplit('.', 1)
     0554:                locs['method'] = getattr(importlib.import_module(module), method)
 *** 0555:                outhash = bb.utils.better_eval('method(path, sigfile, task, d)', locs)
     0556:            else:
     0557:                outhash = bb.utils.better_eval(self.method + '(path, sigfile, task, d)', locs)
     0558:
     0559:            try:
File: '/media/janek/7cd07add-5479-43d8-a522-1292f153b637/workspace/baw/dunfell/m5/bsp-platform-st/sources/poky/bitbake/lib/bb/utils.py', lineno: 420, function: better_eval
     0416:    if extraglobals:
     0417:        ctx = copy.copy(ctx)
     0418:        for g in extraglobals:
     0419:            ctx[g] = extraglobals[g]
 *** 0420:    return eval(source, ctx, locals)
     0421:
     0422:@contextmanager
     0423:def fileslocked(files):
     0424:    """Context manager for locking and unlocking file locks."""
File: '<string>', lineno: 1, function: <module>
  File "<string>", line 1, in <module>

File: '/media/janek/7cd07add-5479-43d8-a522-1292f153b637/workspace/baw/dunfell/m5/bsp-platform-st/sources/poky/meta/lib/oe/sstatesig.py', lineno: 589, function: OEOuthashBasic
     0585:            process(root)
     0586:            for f in files:
     0587:                if f == 'fixmepath':
     0588:                    continue
 *** 0589:                process(os.path.join(root, f))
     0590:    finally:
     0591:        os.chdir(prev_dir)
     0592:
     0593:    return h.hexdigest()
File: '/media/janek/7cd07add-5479-43d8-a522-1292f153b637/workspace/baw/dunfell/m5/bsp-platform-st/sources/poky/meta/lib/oe/sstatesig.py', lineno: 548, function: process
     0544:                    add_perm(stat.S_IXOTH, 'x')
     0545:
     0546:                if include_owners:
     0547:                    try:
 *** 0548:                        update_hash(" %10s" % pwd.getpwuid(s.st_uid).pw_name)
     0549:                        update_hash(" %10s" % grp.getgrgid(s.st_gid).gr_name)
     0550:                    except KeyError:
     0551:                        bb.warn("KeyError in %s" % path)
     0552:                        raise
Exception: KeyError: 'getpwuid(): uid not found: 1000'

ERROR: Logfile of failure stored in: /media/janek/7cd07add-5479-43d8-a522-1292f153b637/workspace/baw/dunfell/m5/bsp-platform-st/build/tmp/work/x86_64-nativesdk-pokysdk-linux/gdb-cross-canadian-arm/9.1-r0/temp/log.do_package.9869
ERROR: Task (/media/janek/7cd07add-5479-43d8-a522-1292f153b637/workspace/baw/dunfell/m5/bsp-platform-st/sources/poky/meta/recipes-devtools/gdb/gdb-cross-canadian_9.1.bb:do_package) failed with exit code '1'